/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectinterfaces.ui;

import projectinterfaces.model.Customer;
import java.util.logging.Logger;
import javafx.beans.value.ObservableValue;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Hyperlink;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javax.ws.rs.InternalServerErrorException;
import javax.ws.rs.NotAuthorizedException;
import projectinterfaces.logic.CustomerRESTClient1;

/**
 * FXML Controller class for the Sign In window.
 * It handles user login, navigation to registration, and application exit.
 * It interacts with the CustomerRESTClient1 for user authentication.
 * @author Luis Felipe Acosta Osorno
 */
public class ProjectInterfacesController {

    @FXML
    private TextField tfEmail;
    @FXML
    private PasswordField pfPassword;
    @FXML
    private Hyperlink Register;
    @FXML
    private Button btnLogin;
    @FXML
    private Button btnExit;
    private static final Logger LOGGER = Logger.getLogger("projectinterfaces.ui");
    private Stage stage;
    private String password;

    public void init(Stage stage, Parent root) {

        //Se crea la escena asociada al grafico de root.
        LOGGER.info("Initializing window");
        //Asociamos la escena a la primera ventana.
        Scene scene = new Scene(root);
        //Se establecen las propiedades de la vetana.
        stage.setScene(scene);
        //Establecer el titulo de la ventana
        stage.setTitle("Sign In");
        //La ventana no es redimensionable
        stage.setResizable(false);
        //El botón Login esta deshabilitado y el botón Exit esta habilitado.
        btnLogin.setDisable(true);
        btnExit.setDisable(false);
        //Asociar eventos a manejadores
        Register.setOnAction(this::handleRegisterOnAction);
        btnLogin.setOnAction(this::handleLoginOnAction);
        btnExit.setOnAction(this::handleExitOnAction);
        tfEmail.textProperty().addListener((
                observable, oldValue, newValue) -> handleChecks());
        pfPassword.textProperty().addListener((
                observable, oldValue, newValue) -> handleChecks());
        tfEmail.focusedProperty().addListener(this::handletfEmailFocusChange);
        pfPassword.focusedProperty().addListener(this::handlepfPasswordFocusChange);

        //Mostrar la ventana
        stage.show();
    }
    /**
    * Initializes the primary stage of the Sign In window.
    * Sets up the scene, stage properties (title, resizable), initial control states,
    * and listeners for field changes and focus, and action handlers for buttons and hyperlink.
     * * @param stage The primary stage of this window.
    * @param root The root node of the FXML layout for this scene.
    */
   

    private void handleAlert(String mensaje) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setContentText(mensaje);
        alert.showAndWait();
    }
    /**
     * Displays an error alert dialog with a specified message.
     * @param mensaje The error message to be displayed in the alert. 
     */

    private void handleRegisterOnAction(ActionEvent event) {
        try {
           
            FXMLLoader loader = new FXMLLoader(
                    getClass().getResource("SignUpController.fxml"));
            Parent root = (Parent) loader.load();
            Scene scene = new Scene(root);
            scene.getRoot();

        } catch (Exception e) {
            LOGGER.warning(e.getMessage());
            handleAlert("¡Error, when going to registry!");
        }
    }
    /**
    * Handles the action when the Register hyperlink is clicked.
    * It attempts to load and navigate to the SignUp window (SignUpController.fxml).
    * Logs and shows an error alert if the navigation fails.
    * * @param event The ActionEvent generated by the hyperlink. 
     */

    private void handleLoginOnAction(ActionEvent event) {
        try {
            //Comprobación de los campos
            /*if (this.tfEmail.getText().trim().equals("")
                    || this.pfPassword.getText().trim().equals("")) {
            }*/
            
            //Crear un objeto customer
            CustomerRESTClient1 client = new CustomerRESTClient1();

            Customer customer = client.findCustomerByEmailPassword_XML(Customer.class,
                    tfEmail.getText().trim(), pfPassword.getText().trim());
            
            Alert alert = new Alert(Alert.AlertType.INFORMATION);
            alert.setContentText("¡Welcome "+customer.getFirstName()+"!");
            alert.showAndWait();
        //Abrir la ventana de change password
        /*FXMLLoader loader = new FXMLLoader(getClass().getResource("ChangePasswordController.fxml"));
        Parent root = (Parent)loader.load();
        ProjectInterfacesController controller = loader.getController();
        
        controller.setCustomer(customer);
        controller.init(stage, root);*/
          

            
        } catch (NotAuthorizedException a) {
            LOGGER.warning(a.getMessage());
            handleAlert("¡The email or password is incorrect!");
            tfEmail.setStyle("-fx-border-color: red; -fx-border-width: 2px;");
            pfPassword.setStyle("-fx-border-color: red; -fx-border-width: 2px;");
            
            
        } catch (InternalServerErrorException b) {
            LOGGER.warning(b.getMessage());
            handleAlert("¡Internal server not found,\n"
                    + "please try again after a few minutes,\n "
                    + "if the problem persists, contact you company!");
            
        } catch (Exception e) {
            LOGGER.warning(e.getMessage());
            handleAlert("¡Email and password must be to filled!");
            tfEmail.setStyle("-fx-border-color: red; -fx-border-width: 2px;");
            pfPassword.setStyle("-fx-border-color: red; -fx-border-width: 2px;");

        }
    }

    /**
    * Handles the action when the Login button is clicked.
    * It authenticates the user by calling the REST client with the provided email and password.
    * On successful login, it displays a welcome message.
    * It handles specific exceptions:
    * - {@link NotAuthorizedException} for incorrect credentials (shows error alert and highlights fields).
    * - {@link InternalServerErrorException} for server-side issues (shows server error alert).
    * - Other exceptions for general errors (e.g., empty fields not caught by checks).
    * * @param event The ActionEvent generated by the Login button.
    */
    
    private void handleChecks() {
        boolean fEmail = fEmail();
        boolean fPassword = fPassword();
        btnLogin.setDisable(!(fEmail && fPassword));
    }
    /**
    * Checks if both the email and password fields are filled.
    * It enables the Login button only if both {@link #fEmail()} and {@link #fPassword()} return true.
    */
    private boolean fEmail() {
        boolean isfEmail = tfEmail.getText().isEmpty();
        return !isfEmail;
    }
    /**
    * Checks if the email text field is *not* empty.
    * * @return true if the email field contains text, false otherwise.
    */

    private boolean fPassword() {
        boolean isfPassword = pfPassword.getText().isEmpty();
        return !isfPassword;
    }
    /**
    * Checks if the password field is *not* empty.
    * * @return true if the password field contains text, false otherwise.
     */

    private void handleExitOnAction(ActionEvent event) {

        Alert alert = new Alert(AlertType.CONFIRMATION,
                "Are you sure you want to go out?",
                ButtonType.YES, ButtonType.NO);
        alert.setTitle("¡Confirm Exit!");
        alert.showAndWait();

        if (alert.getResult() == ButtonType.YES) {
            //Lanzamos la ventana emergente para pedir confirmación de salida
            Stage stage = (Stage) btnExit.getScene().getWindow();
            stage.close();
        }

    }
    /**
    * Handles the action when the Exit button is clicked.
    * It shows a confirmation dialog and closes the application stage if the user confirms.
    * * @param event The ActionEvent generated by the Exit button.
     */
    private void handlepfPasswordFocusChange(ObservableValue observable, 
            boolean oldValue, boolean newValue){
        
        if(newValue){
        pfPassword.setStyle("-fx-border-color: grey; -fx-border-width: 2px;");
        }
        
        
    }
    /**
    * Handles the focus change event for the password field.
    * When the field gains focus (newValue is true), it resets the border style to grey, 
    * removing any previous error highlighting.
    * * @param observable The observable value being listened to.
    * @param oldValue The previous focus state.
    * @param newValue The new focus state (true if the field has focus).
    */
    
    private void handletfEmailFocusChange(ObservableValue observable, 
            boolean oldValue, boolean newValue){
        
            if(newValue){
            tfEmail.setStyle("-fx-border-color: grey; -fx-border-width: 2px;");
            }
    
    }
    /**
    * Handles the focus change event for the email text field.
    * When the field gains focus (newValue is true), it resets the border style to grey, 
    * removing any previous error highlighting.
    * * @param observable The observable value being listened to.
    * @param oldValue The previous focus state.
    * @param newValue The new focus state (true if the field has focus).
    */

}
